# Generated by Django 2.1 on 2018-09-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20180919_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.IntegerField(default=0, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(default=0, verbose_name='CPF'),
        ),
    ]
