# Generated by Django 2.1 on 2018-09-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20180920_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('descricao', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='')),
                ('largura', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('dpt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Departamento')),
            ],
        ),
    ]
