# Generated by Django 2.1 on 2018-09-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_departamento_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='dpt',
        ),
    ]
