# Generated by Django 2.1 on 2018-09-23 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_produto_dpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dpt',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Departamento'),
            preserve_default=False,
        ),
    ]
