# Generated by Django 2.1 on 2018-09-25 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_produto_dpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='dpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Departamento'),
        ),
    ]
