# Generated by Django 2.1 on 2018-09-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20180924_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem2',
            field=models.ImageField(default='padrao.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem3',
            field=models.ImageField(default='padrao.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem4',
            field=models.ImageField(default='padrao.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem5',
            field=models.ImageField(default='padrao.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem6',
            field=models.ImageField(default='padrao.png', upload_to=''),
        ),
    ]
