# Generated by Django 2.1 on 2018-09-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20180925_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
