# Generated by Django 2.1 on 2018-09-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20180926_1718'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['nome_produto'], name='ecommerce_p_nome_pr_4e8542_idx'),
        ),
    ]
