# Generated by Django 2.1 on 2018-09-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20180926_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cep',
        ),
    ]
