# Generated by Django 2.1 on 2018-09-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='sem bairro', max_length=50),
            preserve_default=False,
        ),
    ]
