# Generated by Django 2.1 on 2018-10-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_endereco_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
