# Generated by Django 2.1 on 2018-10-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qtdvendas',
            field=models.IntegerField(default=0),
        ),
    ]
